wikiSite/wikiPage/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'wikiPage'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    path('<path:title_url>/', views.detail, name='detail'),
]

wikiSite/wikiSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('wikiPage/', include('wikiPage.urls')),
    path('admin/', admin.site.urls),
]

wikiSite/wikiPage/models.py
import datetime
from django.utils import timezone
from django.db import models
# Create your models here.

class WiKi(models.Model):
    title_text = models.CharField(max_length=200)
    url_text = models.CharField(max_length=200)
    author_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self): # 管理后台显示
        return self.title_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

wikiSite/wikiPage/views.py
from django.shortcuts import render
import logging
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import redirect
from .models import WiKi
from django.db.models import Q

logger = logging.getLogger(__name__)


def index(request):
    latest_wiki_list = WiKi.objects.order_by('-pub_date')[:100]
    template = loader.get_template('wikiPage/index.html')
    context = {
        'latest_wiki_list': latest_wiki_list,
    }
    return HttpResponse(template.render(context, request))


def detail(request, title_url):
    # return HttpResponse("%s." % question_text)
    return redirect("%s" % title_url)  # url重定向


def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = "请输入关键词"
        return render(request, 'wikiPage/results.html', {'error_msg': error_msg})

    wiki_list = WiKi.objects.filter(Q(title_text__icontains=q) | Q(author_text__icontains=q))
    print("======== %s" % wiki_list.count())
    return render(request, 'wikiPage/results.html', {'error_msg': error_msg,
                                                  'wiki_list': wiki_list})

wikiSite/wikiPage/templates/WikiPage/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

wikiSite/wikiPage/templates/WikiPage/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>wiki 列表</title>
</head>
<body>
    <h2>iOS wiki 列表</h2>

    <form role="search" method="get" id="searchform" action="{% url 'wikiPage:search' %}">
        <input type="search" name="q" placeholder="搜索" required>
        <button type="submit" value="search">搜索标题/作者</button>
    </form>

{% if latest_wiki_list %}
    <ul>
    {% for wiki in latest_wiki_list %}
          <li><a href="{% url 'wikiPage:detail' wiki.url_text %}">{{ wiki.title_text }}</a></li>
           作者: {{ wiki.author_text }}
           &nbsp;&nbsp;&nbsp;上传时间: {{ wiki.pub_date }}
    {% endfor %}
    </ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

wikiSite/wikiPage/templates/WikiPage/results.html
{% block main %}
  {% if error_msg %}
    <p>{{ error_msg }}</p>
  {% endif %}

  {% for wiki in wiki_list %}
      <li><a href="{% url 'wikiPage:detail' wiki.url_text %}">{{ wiki.title_text }}</a></li>
           作者: {{ wiki.author_text }}
           &nbsp;&nbsp;&nbsp;上传时间: {{ wiki.pub_date }}
  {% empty %}
    <div class="no-post">没找到对应的wiki</div>
  {% endfor %}
{% endblock main %}